"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import map_geometry_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ChatEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SENDER_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    sender: builtins.int
    message: builtins.str
    def __init__(
        self,
        *,
        sender: builtins.int | None = ...,
        message: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["message", b"message", "sender", b"sender"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "sender", b"sender"]) -> None: ...

global___ChatEvent = ChatEvent

@typing.final
class MapLoadEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MAP_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    SERVER_FIELD_NUMBER: builtins.int
    DATETIME_FIELD_NUMBER: builtins.int
    SERVER_IP_FIELD_NUMBER: builtins.int
    PROTOCOL_VERSION_FIELD_NUMBER: builtins.int
    name: builtins.str
    server: builtins.str
    datetime: builtins.str
    server_ip: builtins.str
    protocol_version: builtins.str
    @property
    def map(self) -> map_geometry_pb2.MapGeometry: ...
    def __init__(
        self,
        *,
        map: map_geometry_pb2.MapGeometry | None = ...,
        name: builtins.str | None = ...,
        server: builtins.str | None = ...,
        datetime: builtins.str | None = ...,
        server_ip: builtins.str | None = ...,
        protocol_version: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["datetime", b"datetime", "map", b"map", "name", b"name", "protocol_version", b"protocol_version", "server", b"server", "server_ip", b"server_ip"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["datetime", b"datetime", "map", b"map", "name", b"name", "protocol_version", b"protocol_version", "server", b"server", "server_ip", b"server_ip"]) -> None: ...

global___MapLoadEvent = MapLoadEvent

@typing.final
class SetPlayerEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    TEAM_FIELD_NUMBER: builtins.int
    LEVEL_FIELD_NUMBER: builtins.int
    ACE_RANK_FIELD_NUMBER: builtins.int
    VAPOR_FIELD_NUMBER: builtins.int
    id: builtins.int
    name: builtins.str
    team: builtins.int
    level: builtins.int
    ace_rank: builtins.int
    vapor: builtins.str
    def __init__(
        self,
        *,
        id: builtins.int | None = ...,
        name: builtins.str | None = ...,
        team: builtins.int | None = ...,
        level: builtins.int | None = ...,
        ace_rank: builtins.int | None = ...,
        vapor: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["ace_rank", b"ace_rank", "id", b"id", "level", b"level", "name", b"name", "team", b"team", "vapor", b"vapor"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["ace_rank", b"ace_rank", "id", b"id", "level", b"level", "name", b"name", "team", b"team", "vapor", b"vapor"]) -> None: ...

global___SetPlayerEvent = SetPlayerEvent

@typing.final
class RemovePlayerEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.int
    def __init__(
        self,
        *,
        id: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["id", b"id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["id", b"id"]) -> None: ...

global___RemovePlayerEvent = RemovePlayerEvent

@typing.final
class GoalEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WHO_SCORED_FIELD_NUMBER: builtins.int
    @property
    def who_scored(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """optional uint32 team = 1; // removed, do not use
        first is scorer, next are assists
        """

    def __init__(
        self,
        *,
        who_scored: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["who_scored", b"who_scored"]) -> None: ...

global___GoalEvent = GoalEvent

@typing.final
class KillEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WHO_KILLED_FIELD_NUMBER: builtins.int
    WHO_DIED_FIELD_NUMBER: builtins.int
    who_killed: builtins.int
    """if not assigned, was a crash"""
    who_died: builtins.int
    def __init__(
        self,
        *,
        who_killed: builtins.int | None = ...,
        who_died: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["who_died", b"who_died", "who_killed", b"who_killed"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["who_died", b"who_died", "who_killed", b"who_killed"]) -> None: ...

global___KillEvent = KillEvent

@typing.final
class DamageEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SOURCE_FIELD_NUMBER: builtins.int
    TARGET_FIELD_NUMBER: builtins.int
    AMOUNT_FIELD_NUMBER: builtins.int
    ANGLE_FIELD_NUMBER: builtins.int
    source: builtins.int
    target: builtins.int
    amount: builtins.int
    """in tenths of a hp"""
    angle: builtins.int
    def __init__(
        self,
        *,
        source: builtins.int | None = ...,
        target: builtins.int | None = ...,
        amount: builtins.int | None = ...,
        angle: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["amount", b"amount", "angle", b"angle", "source", b"source", "target", b"target"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["amount", b"amount", "angle", b"angle", "source", b"source", "target", b"target"]) -> None: ...

global___DamageEvent = DamageEvent

@typing.final
class MetaEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    data: builtins.str
    def __init__(
        self,
        *,
        data: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["data", b"data"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["data", b"data"]) -> None: ...

global___MetaEvent = MetaEvent

@typing.final
class GameEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHAT_FIELD_NUMBER: builtins.int
    MAP_LOAD_FIELD_NUMBER: builtins.int
    SET_PLAYER_FIELD_NUMBER: builtins.int
    REMOVE_PLAYER_FIELD_NUMBER: builtins.int
    GOAL_FIELD_NUMBER: builtins.int
    KILL_FIELD_NUMBER: builtins.int
    DAMAGE_FIELD_NUMBER: builtins.int
    META_FIELD_NUMBER: builtins.int
    @property
    def chat(self) -> global___ChatEvent: ...
    @property
    def map_load(self) -> global___MapLoadEvent: ...
    @property
    def set_player(self) -> global___SetPlayerEvent: ...
    @property
    def remove_player(self) -> global___RemovePlayerEvent: ...
    @property
    def goal(self) -> global___GoalEvent: ...
    @property
    def kill(self) -> global___KillEvent: ...
    @property
    def damage(self) -> global___DamageEvent: ...
    @property
    def meta(self) -> global___MetaEvent: ...
    def __init__(
        self,
        *,
        chat: global___ChatEvent | None = ...,
        map_load: global___MapLoadEvent | None = ...,
        set_player: global___SetPlayerEvent | None = ...,
        remove_player: global___RemovePlayerEvent | None = ...,
        goal: global___GoalEvent | None = ...,
        kill: global___KillEvent | None = ...,
        damage: global___DamageEvent | None = ...,
        meta: global___MetaEvent | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["chat", b"chat", "damage", b"damage", "event", b"event", "goal", b"goal", "kill", b"kill", "map_load", b"map_load", "meta", b"meta", "remove_player", b"remove_player", "set_player", b"set_player"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["chat", b"chat", "damage", b"damage", "event", b"event", "goal", b"goal", "kill", b"kill", "map_load", b"map_load", "meta", b"meta", "remove_player", b"remove_player", "set_player", b"set_player"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["event", b"event"]) -> typing.Literal["chat", "map_load", "set_player", "remove_player", "goal", "kill", "damage", "meta"] | None: ...

global___GameEvent = GameEvent
