# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: update.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'update.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import game_object_pb2 as game__object__pb2
from . import game_event_pb2 as game__event__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cupdate.proto\x1a\x11game_object.proto\x1a\x10game_event.proto\"P\n\x06Update\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12\x1c\n\x07objects\x18\x02 \x03(\x0b\x32\x0b.GameObject\x12\x1a\n\x06\x65vents\x18\x03 \x03(\x0b\x32\n.GameEventB\x1b\n\x17\x65m.altitude.game.protosP\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'update_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027em.altitude.game.protosP\001'
  _globals['_UPDATE']._serialized_start=53
  _globals['_UPDATE']._serialized_end=133
# @@protoc_insertion_point(module_scope)
