name: dev

x-db-env: &db-env
  POSTGRES_HOST: altistats.com
  POSTGRES_PORT: 5432
  POSTGRES_USER: root
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: altistats

services:
  # nginx:
  #   build: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ${ALTI_HOME}/recordings/:/usr/share/nginx/recordings/
  #   restart: unless-stopped

  # site:
  #   build: site
  #   environment:
  #     <<: *db-env
  #   ports:
  #     - "3000:3000"

  bot:
    build:
      context: ../java_dist/
      dockerfile: botclient.Dockerfile
    deploy:
      mode: global
    volumes:
      - ../alti_home/:/app
    environment:
      JAVA_OPTS: -Xmx512m
      ALTI_HOME: /app
      BOT_CONFIG: /app/client_configs/spectate_ladder_test.xml
      <<: *db-env
