name: dev

x-db-env: &db-env
  POSTGRES_HOST: altistats.com
  POSTGRES_PORT: 5432
  POSTGRES_USER: root
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: altistats

services:
  # nginx:
  #   build: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ${ALTI_HOME}/recordings/:/usr/share/nginx/recordings/
  #   restart: unless-stopped

  # site:
  #   build: site
  #   volumes:
  #     - ../stats_db/:/app/stats_db
  #   environment:
  #     STATS_DB: /app/stats_db/stats.db
  #     <<: *db-env
  #   ports:
  #     - "3000:3000"

  # bot:
  #   build:
  #     context: ../java_dist/
  #     dockerfile: botclient.Dockerfile
  #   deploy:
  #     mode: global
  #   volumes:
  #     - ../alti_home/:/app
  #   environment:
  #     JAVA_OPTS: -Xmx512m
  #     ALTI_HOME: /app
  #     BOT_CONFIG: /app/client_configs/test.xml
  #     <<: *db-env

  stats_db:
    build:
      context: ../stats_db/
      dockerfile: Dockerfile
    volumes:
      - ${REPLAY_DIR}:/app/replays:ro
      - ../stats_db/:/app/stats_db
    environment:
      REPLAY_DIR: /app/replays/
      STATS_DB: /app/stats_db/stats.db
      STATS_INTERVAL: 60
    restart: unless-stopped
