set dotenv-load

dev:
	docker context use default
	docker compose -f dev.yml up -d --remove-orphans --build

# Docker compose

COMPOSE := "docker --host \"ssh://root@altistats.com\" compose -f prod.yml"

down:
	{{ COMPOSE }} down

up:
	{{ COMPOSE }} up -d --remove-orphans

reset-stats:
	{{ COMPOSE }} down stats_db
	ssh root@altistats.com "rm -rf /root/alti_home/stats_db"
	rsync -va ../stats_db/stats.db* root@altistats.com:/root/alti_home/stats_db/
	{{ COMPOSE }} up stats_db

log service:
	{{ COMPOSE }} logs --since 30m -f {{ service }}

restart-bots:
	./scripts/make_configs.py
	rsync -rhv build/client_configs/ root@altistats.com:/root/alti_home/client_configs/
	{{ COMPOSE }} restart spec-bot-1 spec-bot-2 spec-bot-3 spec-bot-4 spec-bot-5

pull:
	./scripts/make_configs.py
	rsync -rhv build/client_configs/ root@altistats.com:/root/alti_home/client_configs/
	{{ COMPOSE }} pull

docker_plat := "--platform=linux/amd64"

upload-stats:
	docker context use default
	docker build {{ docker_plat }} -t magneticduck/stats_db:latest ../stats_db
	docker push magneticduck/stats_db:latest

upload-site:
	docker context use default
	docker build {{ docker_plat }} -t magneticduck/altistats:latest site
	docker push magneticduck/altistats:latest

BOT_IMAGE := "magneticduck/botclient:0.3.1"

upload-bot:
	docker context use default
	docker build {{ docker_plat }} -t {{ BOT_IMAGE }} \
		-f ../java_dist/botclient.Dockerfile ../java_dist
	docker push {{ BOT_IMAGE }}

list-servers:
	psql -P pager=off -c "\
		SELECT * FROM (\
			SELECT DISTINCT ON (ip) \
				ip, map, name, players AS max_players, time AS peak_time \
			FROM listings \
			WHERE players > 0 AND time >= NOW() - INTERVAL '7 days' \
			ORDER BY ip, players DESC, time DESC \
		) sub \
		ORDER BY max_players DESC;"

restart-listing:
	docker --host "ssh://root@altistats.com" compose -f prod.yml restart listing-bot
