set dotenv-load

# Index replays into our database
index:
	# make -C .. bin/index
	index --replays ${REPLAY_DIR} \
		--out "host=altistats.com user=root password=${PGPASSWORD} dbname=altistats" \
		--progress

update-views:
	cat sql/views.sql | psql

dev:
	docker context use default
	docker compose -f dev.yml up --remove-orphans --build

# Run a query from site/sql/
query file *args:
    psql -f site/sql/{{file}}.sql {{args}}

# Docker compose

up:
	docker --host "ssh://root@altistats.com" compose -f prod.yml pull
	docker --host "ssh://root@altistats.com" compose -f prod.yml up -d --build

docker_plat := "--platform=linux/amd64"

upload-site:
	docker build {{docker_plat}} -t magneticduck/altistats:latest site
	docker push magneticduck/altistats:latest

upload-bot:
	docker build {{docker_plat}} -t magneticduck/botclient:latest \
		-f ../java_dist/botclient.Dockerfile ../java_dist
	docker push magneticduck/botclient:latest
