name: altistats

x-db-env: &db-env
  POSTGRES_USER: root
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: altistats
  POSTGRES_HOST: pg
  POSTGRES_PORT: 5432

x-bot-base: &bot-base
  image: magneticduck/botclient:latest
  deploy:
    mode: global
  volumes:
    - /root/alti_home:/app
  restart: unless-stopped

services:
  nginx:
    build: nginx
    ports:
      - "80:80"
    volumes:
      - /root/alti_home/recordings/:/usr/share/nginx/recordings/
      - /root/files/:/usr/share/nginx/files/
    restart: unless-stopped

  stats_db:
    image: magneticduck/stats_db:latest
    volumes:
      - /root/alti_home/recordings:/app/recordings:ro
      - /root/stats_db/:/app/stats_db/
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: 2G
    environment:
      REPLAY_DIR: /app/recordings/
      STATS_DB: /app/stats_db/stats.db
      STATS_INTERVAL: 60
    restart: unless-stopped

  site:
    image: magneticduck/altistats:latest
    volumes:
      - /root/stats_db/:/app/stats_db/
    environment:
      <<: *db-env
      STATS_DB: /app/stats_db/stats.db
      NODE_ENV: production
    ports:
      - "3000:3000"
    restart: unless-stopped

  listing-bot:
    <<: *bot-base
    environment:
      BOT_CONFIG: /app/client_configs/get_listings.xml
      ALTI_HOME: /app
      <<: *db-env

    depends_on:
      - pg

  spec-bot-1:
    <<: *bot-base
    environment:
      BOT_CONFIG: /app/client_configs/spectate_ladder_1.xml
      JAVA_OPTS: -Xmx512m
      ALTI_HOME: /app

  spec-bot-2:
    <<: *bot-base
    environment:
      BOT_CONFIG: /app/client_configs/spectate_ladder_2.xml
      JAVA_OPTS: -Xmx512m
      ALTI_HOME: /app

  pg:
    image: postgres:15
    deploy:
      mode: global
    environment:
      <<: *db-env
    volumes:
      - /root/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
