"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import game_object_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _TeamTarget:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _TeamTargetEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TeamTarget.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    TEAM_SPEC: _TeamTarget.ValueType  # 1
    TEAM_LEFT: _TeamTarget.ValueType  # 2
    TEAM_RIGHT: _TeamTarget.ValueType  # 3
    TEAM_AUTO: _TeamTarget.ValueType  # 4

class TeamTarget(_TeamTarget, metaclass=_TeamTargetEnumTypeWrapper): ...

TEAM_SPEC: TeamTarget.ValueType  # 1
TEAM_LEFT: TeamTarget.ValueType  # 2
TEAM_RIGHT: TeamTarget.ValueType  # 3
TEAM_AUTO: TeamTarget.ValueType  # 4
global___TeamTarget = TeamTarget

@typing_extensions.final
class SetOptionsCmd(google.protobuf.message.Message):
    """set general options"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___SetOptionsCmd = SetOptionsCmd

@typing_extensions.final
class SetMapCmd(google.protobuf.message.Message):
    """switch/reset the map"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MAP_FIELD_NUMBER: builtins.int
    map: builtins.str
    def __init__(
        self,
        *,
        map: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["map", b"map"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["map", b"map"]) -> None: ...

global___SetMapCmd = SetMapCmd

@typing_extensions.final
class StartRecordCmd(google.protobuf.message.Message):
    """start a new recording, save old"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["name", b"name"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["name", b"name"]) -> None: ...

global___StartRecordCmd = StartRecordCmd

@typing_extensions.final
class StopRecordCmd(google.protobuf.message.Message):
    """save recording"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___StopRecordCmd = StopRecordCmd

@typing_extensions.final
class ConfigCmd(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REDPERK_FIELD_NUMBER: builtins.int
    BLUEPERK_FIELD_NUMBER: builtins.int
    GREENPERK_FIELD_NUMBER: builtins.int
    TEAM_FIELD_NUMBER: builtins.int
    redPerk: game_object_pb2.Perk.ValueType
    bluePerk: game_object_pb2.Perk.ValueType
    greenPerk: game_object_pb2.Perk.ValueType
    team: global___TeamTarget.ValueType
    def __init__(
        self,
        *,
        redPerk: game_object_pb2.Perk.ValueType | None = ...,
        bluePerk: game_object_pb2.Perk.ValueType | None = ...,
        greenPerk: game_object_pb2.Perk.ValueType | None = ...,
        team: global___TeamTarget.ValueType | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["bluePerk", b"bluePerk", "greenPerk", b"greenPerk", "redPerk", b"redPerk", "team", b"team"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["bluePerk", b"bluePerk", "greenPerk", b"greenPerk", "redPerk", b"redPerk", "team", b"team"]) -> None: ...

global___ConfigCmd = ConfigCmd

@typing_extensions.final
class InputCmd(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTROLS_FIELD_NUMBER: builtins.int
    controls: builtins.int
    """up + down << 1 + left << 2 + right << 3
    + f << 4 + d << 5 + s << 6
    """
    def __init__(
        self,
        *,
        controls: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["controls", b"controls"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["controls", b"controls"]) -> None: ...

global___InputCmd = InputCmd

@typing_extensions.final
class Cmd(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class ConfigsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.int
        @property
        def value(self) -> global___ConfigCmd: ...
        def __init__(
            self,
            *,
            key: builtins.int | None = ...,
            value: global___ConfigCmd | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    @typing_extensions.final
    class InputsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.int
        @property
        def value(self) -> global___InputCmd: ...
        def __init__(
            self,
            *,
            key: builtins.int | None = ...,
            value: global___InputCmd | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    SETOPTIONS_FIELD_NUMBER: builtins.int
    SETMAP_FIELD_NUMBER: builtins.int
    STOPRECORD_FIELD_NUMBER: builtins.int
    STARTRECORD_FIELD_NUMBER: builtins.int
    CONFIGS_FIELD_NUMBER: builtins.int
    INPUTS_FIELD_NUMBER: builtins.int
    @property
    def setOptions(self) -> global___SetOptionsCmd: ...
    @property
    def setMap(self) -> global___SetMapCmd:
        """only for bot server"""
    @property
    def stopRecord(self) -> global___StopRecordCmd:
        """recordings"""
    @property
    def startRecord(self) -> global___StartRecordCmd: ...
    @property
    def configs(self) -> google.protobuf.internal.containers.MessageMap[builtins.int, global___ConfigCmd]:
        """input and configs"""
    @property
    def inputs(self) -> google.protobuf.internal.containers.MessageMap[builtins.int, global___InputCmd]: ...
    def __init__(
        self,
        *,
        setOptions: global___SetOptionsCmd | None = ...,
        setMap: global___SetMapCmd | None = ...,
        stopRecord: global___StopRecordCmd | None = ...,
        startRecord: global___StartRecordCmd | None = ...,
        configs: collections.abc.Mapping[builtins.int, global___ConfigCmd] | None = ...,
        inputs: collections.abc.Mapping[builtins.int, global___InputCmd] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["setMap", b"setMap", "setOptions", b"setOptions", "startRecord", b"startRecord", "stopRecord", b"stopRecord"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["configs", b"configs", "inputs", b"inputs", "setMap", b"setMap", "setOptions", b"setOptions", "startRecord", b"startRecord", "stopRecord", b"stopRecord"]) -> None: ...

global___Cmd = Cmd
