# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import game_object_pb2 as game__object__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcommand.proto\x1a\x11game_object.proto\"\x0f\n\rSetOptionsCmd\"\x18\n\tSetMapCmd\x12\x0b\n\x03map\x18\x01 \x01(\t\"\x1e\n\x0eStartRecordCmd\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x0f\n\rStopRecordCmd\"q\n\tConfigCmd\x12\x16\n\x07redPerk\x18\x01 \x01(\x0e\x32\x05.Perk\x12\x17\n\x08\x62luePerk\x18\x02 \x01(\x0e\x32\x05.Perk\x12\x18\n\tgreenPerk\x18\x03 \x01(\x0e\x32\x05.Perk\x12\x19\n\x04team\x18\x04 \x01(\x0e\x32\x0b.TeamTarget\"\x1c\n\x08InputCmd\x12\x10\n\x08\x63ontrols\x18\x01 \x01(\r\"\xcb\x02\n\x03\x43md\x12\"\n\nsetOptions\x18\x01 \x01(\x0b\x32\x0e.SetOptionsCmd\x12\x1a\n\x06setMap\x18\x02 \x01(\x0b\x32\n.SetMapCmd\x12\"\n\nstopRecord\x18\n \x01(\x0b\x32\x0e.StopRecordCmd\x12$\n\x0bstartRecord\x18\x0b \x01(\x0b\x32\x0f.StartRecordCmd\x12\"\n\x07\x63onfigs\x18\x15 \x03(\x0b\x32\x11.Cmd.ConfigsEntry\x12 \n\x06inputs\x18\x16 \x03(\x0b\x32\x10.Cmd.InputsEntry\x1a:\n\x0c\x43onfigsEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x19\n\x05value\x18\x02 \x01(\x0b\x32\n.ConfigCmd:\x02\x38\x01\x1a\x38\n\x0bInputsEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x18\n\x05value\x18\x02 \x01(\x0b\x32\t.InputCmd:\x02\x38\x01*I\n\nTeamTarget\x12\r\n\tTEAM_SPEC\x10\x01\x12\r\n\tTEAM_LEFT\x10\x02\x12\x0e\n\nTEAM_RIGHT\x10\x03\x12\r\n\tTEAM_AUTO\x10\x04\x42\x1b\n\x17\x65m.altitude.game.protosP\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'command_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027em.altitude.game.protosP\001'
  _globals['_CMD_CONFIGSENTRY']._options = None
  _globals['_CMD_CONFIGSENTRY']._serialized_options = b'8\001'
  _globals['_CMD_INPUTSENTRY']._options = None
  _globals['_CMD_INPUTSENTRY']._serialized_options = b'8\001'
  _globals['_TEAMTARGET']._serialized_start=607
  _globals['_TEAMTARGET']._serialized_end=680
  _globals['_SETOPTIONSCMD']._serialized_start=36
  _globals['_SETOPTIONSCMD']._serialized_end=51
  _globals['_SETMAPCMD']._serialized_start=53
  _globals['_SETMAPCMD']._serialized_end=77
  _globals['_STARTRECORDCMD']._serialized_start=79
  _globals['_STARTRECORDCMD']._serialized_end=109
  _globals['_STOPRECORDCMD']._serialized_start=111
  _globals['_STOPRECORDCMD']._serialized_end=126
  _globals['_CONFIGCMD']._serialized_start=128
  _globals['_CONFIGCMD']._serialized_end=241
  _globals['_INPUTCMD']._serialized_start=243
  _globals['_INPUTCMD']._serialized_end=271
  _globals['_CMD']._serialized_start=274
  _globals['_CMD']._serialized_end=605
  _globals['_CMD_CONFIGSENTRY']._serialized_start=489
  _globals['_CMD_CONFIGSENTRY']._serialized_end=547
  _globals['_CMD_INPUTSENTRY']._serialized_start=549
  _globals['_CMD_INPUTSENTRY']._serialized_end=605
# @@protoc_insertion_point(module_scope)
