# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: poly.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import game_object_pb2 as game__object__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npoly.proto\x1a\x11game_object.proto\"_\n\x04Poly\x12\x19\n\x04type\x18\x01 \x01(\x0e\x32\x0b.ObjectType\x12\x16\n\nvertices_x\x18\x02 \x03(\x02\x42\x02\x10\x01\x12\x16\n\nvertices_y\x18\x03 \x03(\x02\x42\x02\x10\x01\x12\x0c\n\x04spin\x18\x04 \x01(\x11')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'poly_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_POLY'].fields_by_name['vertices_x']._options = None
  _globals['_POLY'].fields_by_name['vertices_x']._serialized_options = b'\020\001'
  _globals['_POLY'].fields_by_name['vertices_y']._options = None
  _globals['_POLY'].fields_by_name['vertices_y']._serialized_options = b'\020\001'
  _globals['_POLY']._serialized_start=33
  _globals['_POLY']._serialized_end=128
# @@protoc_insertion_point(module_scope)
