"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import game_object_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Poly(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    VERTICES_X_FIELD_NUMBER: builtins.int
    VERTICES_Y_FIELD_NUMBER: builtins.int
    SPIN_FIELD_NUMBER: builtins.int
    type: game_object_pb2.ObjectType.ValueType
    spin: builtins.int
    """spin in degrees, for planes"""
    @property
    def vertices_x(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def vertices_y(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    def __init__(
        self,
        *,
        type: game_object_pb2.ObjectType.ValueType | None = ...,
        vertices_x: collections.abc.Iterable[builtins.float] | None = ...,
        vertices_y: collections.abc.Iterable[builtins.float] | None = ...,
        spin: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["spin", b"spin", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["spin", b"spin", "type", b"type", "vertices_x", b"vertices_x", "vertices_y", b"vertices_y"]) -> None: ...

global___Poly = Poly
