"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class InputCmd(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTROLS_FIELD_NUMBER: builtins.int
    controls: builtins.int
    """up + down << 1 + left << 2 + right << 3
    + f << 4 + d << 5 + s << 6
    """
    def __init__(
        self,
        *,
        controls: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["controls", b"controls"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["controls", b"controls"]) -> None: ...

global___InputCmd = InputCmd

@typing.final
class Cmd(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class InputsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.int
        @property
        def value(self) -> global___InputCmd: ...
        def __init__(
            self,
            *,
            key: builtins.int | None = ...,
            value: global___InputCmd | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    INPUTS_FIELD_NUMBER: builtins.int
    SHUTDOWN_FIELD_NUMBER: builtins.int
    shutdown: builtins.bool
    @property
    def inputs(self) -> google.protobuf.internal.containers.MessageMap[builtins.int, global___InputCmd]: ...
    def __init__(
        self,
        *,
        inputs: collections.abc.Mapping[builtins.int, global___InputCmd] | None = ...,
        shutdown: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["shutdown", b"shutdown"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["inputs", b"inputs", "shutdown", b"shutdown"]) -> None: ...

global___Cmd = Cmd
