# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: map_geometry.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'map_geometry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12map_geometry.proto\"<\n\nConvexHull\x12\x16\n\nvertices_x\x18\x01 \x03(\x05\x42\x02\x10\x01\x12\x16\n\nvertices_y\x18\x02 \x03(\x05\x42\x02\x10\x01\"e\n\x0f\x43oncaveObstacle\x12\x16\n\nvertices_x\x18\x01 \x03(\x05\x42\x02\x10\x01\x12\x16\n\nvertices_y\x18\x02 \x03(\x05\x42\x02\x10\x01\x12\"\n\rdecomposition\x18\x03 \x03(\x0b\x32\x0b.ConvexHull\"P\n\x0bMapGeometry\x12\r\n\x05max_x\x18\x01 \x01(\r\x12\r\n\x05max_y\x18\x02 \x01(\r\x12#\n\tobstacles\x18\x05 \x03(\x0b\x32\x10.ConcaveObstacleB\x1b\n\x17\x65m.altitude.game.protosP\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'map_geometry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027em.altitude.game.protosP\001'
  _globals['_CONVEXHULL'].fields_by_name['vertices_x']._loaded_options = None
  _globals['_CONVEXHULL'].fields_by_name['vertices_x']._serialized_options = b'\020\001'
  _globals['_CONVEXHULL'].fields_by_name['vertices_y']._loaded_options = None
  _globals['_CONVEXHULL'].fields_by_name['vertices_y']._serialized_options = b'\020\001'
  _globals['_CONCAVEOBSTACLE'].fields_by_name['vertices_x']._loaded_options = None
  _globals['_CONCAVEOBSTACLE'].fields_by_name['vertices_x']._serialized_options = b'\020\001'
  _globals['_CONCAVEOBSTACLE'].fields_by_name['vertices_y']._loaded_options = None
  _globals['_CONCAVEOBSTACLE'].fields_by_name['vertices_y']._serialized_options = b'\020\001'
  _globals['_CONVEXHULL']._serialized_start=22
  _globals['_CONVEXHULL']._serialized_end=82
  _globals['_CONCAVEOBSTACLE']._serialized_start=84
  _globals['_CONCAVEOBSTACLE']._serialized_end=185
  _globals['_MAPGEOMETRY']._serialized_start=187
  _globals['_MAPGEOMETRY']._serialized_end=267
# @@protoc_insertion_point(module_scope)
