"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ConvexHull(google.protobuf.message.Message):
    """Units are whole pixels everywhere.
    We're using int32 instead of uint32 because some geometry may clip outside.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VERTICES_X_FIELD_NUMBER: builtins.int
    VERTICES_Y_FIELD_NUMBER: builtins.int
    @property
    def vertices_x(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def vertices_y(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        vertices_x: collections.abc.Iterable[builtins.int] | None = ...,
        vertices_y: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["vertices_x", b"vertices_x", "vertices_y", b"vertices_y"]) -> None: ...

global___ConvexHull = ConvexHull

@typing.final
class ConcaveObstacle(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VERTICES_X_FIELD_NUMBER: builtins.int
    VERTICES_Y_FIELD_NUMBER: builtins.int
    DECOMPOSITION_FIELD_NUMBER: builtins.int
    @property
    def vertices_x(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def vertices_y(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def decomposition(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ConvexHull]: ...
    def __init__(
        self,
        *,
        vertices_x: collections.abc.Iterable[builtins.int] | None = ...,
        vertices_y: collections.abc.Iterable[builtins.int] | None = ...,
        decomposition: collections.abc.Iterable[global___ConvexHull] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["decomposition", b"decomposition", "vertices_x", b"vertices_x", "vertices_y", b"vertices_y"]) -> None: ...

global___ConcaveObstacle = ConcaveObstacle

@typing.final
class MapGeometry(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MAX_X_FIELD_NUMBER: builtins.int
    MAX_Y_FIELD_NUMBER: builtins.int
    OBSTACLES_FIELD_NUMBER: builtins.int
    max_x: builtins.int
    """Minimum for x and y are 0."""
    max_y: builtins.int
    @property
    def obstacles(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ConcaveObstacle]: ...
    def __init__(
        self,
        *,
        max_x: builtins.int | None = ...,
        max_y: builtins.int | None = ...,
        obstacles: collections.abc.Iterable[global___ConcaveObstacle] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["max_x", b"max_x", "max_y", b"max_y"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["max_x", b"max_x", "max_y", b"max_y", "obstacles", b"obstacles"]) -> None: ...

global___MapGeometry = MapGeometry
