[project]
name = "rl"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "altitude-rl",
    "ipykernel>=6.29.5",
    "jupyterlab-vim>=4.1.4",
    "jupytext>=1.16.7",
    "matplotlib>=3.10.1",
    "tqdm>=4.67.1",
]

[tool.uv.sources]
altitude-rl = { path = "../lib", editable = true }
