benchmark:
	SERVER_CONFIG=./server_benchmark.xml \
	SERVER_RUNTIME="" \
		server

index:
	make -C .. bin/index-lite
	index-lite --path ${ALTI_HOME}/recordings \
		--db ${ALTI_HOME}/recordings.db

view:
	mkdir -p viewer/js
	cp ../hx_src/out/viewer.js viewer/js/
	cd viewer && \
		DB_PATH=${ALTI_HOME}/recordings.db \
		uv run app.py
