[project]
name = "autotude-viewer"
version = "0.1.0"
description = "Web viewer for Altitude replays"
requires-python = ">=3.8"
dependencies = [
    "flask>=3.0.3",
    "pandas>=2.0.3",
    "pytz>=2025.1",
]
