# dumping
dump:
	rm -f test.db
	sqlite3 test.db < schema/data.sql
	cargo run --release --bin dump -- --db test.db --limit 100

dump-one stem:
	rm -f test.db
	sqlite3 test.db < schema/data.sql
	cargo run --release --bin dump -- --db test.db --stem {{stem}}

dump-all:
	rm -f altistats.db
	sqlite3 altistats.db < schema/data.sql
	cargo run --release --bin dump -- --db altistats.db


# loading views and names
load-names:
		sqlite3 altistats.db "DROP TABLE IF EXISTS names; CREATE TABLE names (vapor TEXT, name TEXT);"
		sqlite3 altistats.db ".mode csv" ".import some_players.csv names"
		sqlite3 altistats.db "DROP TABLE IF EXISTS plane_names; CREATE TABLE plane_names (id INTEGER, name TEXT);"
		sqlite3 altistats.db ".mode csv" ".import plane_names.csv plane_names"
		sqlite3 altistats.db "DROP TABLE IF EXISTS perk_names; CREATE TABLE perk_names (id INTEGER, name TEXT);"
		sqlite3 altistats.db ".mode csv" ".import perk_names.csv perk_names"

load-views:
	sqlite3 altistats.db < schema/views.sql

# queries
query name:
	sqlite3 altistats.db -table < sql/{{name}}.sql


# uploading results
upload-players:
	sqlite3 altistats.db -table < sql/players.sql > players.txt
	rsync players.txt --progress root@cgad.ski:/www/files/players.txt

upload-db:
	tar -czf altistats.db.tar altistats.db
	rsync altistats.db.tar --progress root@cgad.ski:/www/files/altistats.db.tar
