dump:
	rm -f altistats.db
	sqlite3 altistats.db < schema/data.sql
	cargo run --release --bin dump -- --db altistats.db --limit 100

dump-all:
	rm -f altistats.db
	sqlite3 altistats.db < schema/data.sql
	cargo run --release --bin dump -- --db altistats.db

query:
	sqlite3 altistats.db < sql/{{name}}.sql
